### PR TITLE
Merge pull request #1 from Legend-of-iPhoenix/master

### PR DESCRIPTION
**Pull request by josheewa**
Update your repo, please.

### CODE REVIEW

**Comment by josheewa** [comment]
@Legend-of-iPhoenix Only merge this if it updates my repo :P

**Comment by Legend-of-iPhoenix** [comment]
Nope lol

**Comment by josheewa** [comment]
How do I update then? @Legend-of-iPhoenix

**Comment by Legend-of-iPhoenix** [comment]
You make the base fork your branch (jcgter777/master) and the head fork my branch (Legend-of-iPhoenix/master).

**Comment by josheewa** [comment]
kk, I'll try.

**Pull request closed without merging**
